# Generated by Django 3.1.3 on 2021-01-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='slug',
            field=models.SlugField(default=0, verbose_name='Atalho'),
            preserve_default=False,
        ),
    ]
