# Generated by Django 3.1.3 on 2020-11-27 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apresentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_title', models.CharField(max_length=200, verbose_name='Título')),
                ('ap_slug', models.SlugField(verbose_name='Atalho')),
                ('ap_text', models.TextField(verbose_name='Texto')),
                ('ap_img1', models.ImageField(blank=True, null=True, upload_to='portfolio_posts/images', verbose_name='Imagem1')),
                ('ap_img2', models.ImageField(blank=True, null=True, upload_to='portfolio_posts/images', verbose_name='Imagem2')),
                ('ap_img3', models.ImageField(blank=True, null=True, upload_to='portfolio_posts/images', verbose_name='Imagem3')),
                ('ap_published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Apresentação',
                'verbose_name_plural': 'Apresentações',
                'ordering': ['ap_published_date'],
            },
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_title', models.CharField(max_length=200, verbose_name='Título')),
                ('art_slug', models.SlugField(verbose_name='Atalho')),
                ('art_text', models.TextField(verbose_name='Texto')),
                ('art_img1', models.ImageField(blank=True, null=True, upload_to='portfolio_posts/images', verbose_name='Imagem1')),
                ('art_img2', models.ImageField(blank=True, null=True, upload_to='portfolio_posts/images', verbose_name='Imagem2')),
                ('art_published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Artigo',
                'verbose_name_plural': 'Artigos',
                'ordering': ['art_published_date'],
            },
        ),
        migrations.CreateModel(
            name='Eletronica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('el_title', models.CharField(max_length=200, verbose_name='Título')),
                ('el_slug', models.SlugField(verbose_name='Atalho')),
                ('el_text', models.TextField(verbose_name='Texto')),
                ('el_img1', models.ImageField(blank=True, null=True, upload_to='portfolio_posts/images', verbose_name='Imagem1')),
                ('el_img2', models.ImageField(blank=True, null=True, upload_to='portfolio_posts/images', verbose_name='Imagem2')),
                ('el_img3', models.ImageField(blank=True, null=True, upload_to='portfolio_posts/images', verbose_name='Imagem3')),
                ('el_published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Eletrônica',
                'verbose_name_plural': 'Eletrônicas',
                'ordering': ['el_published_date'],
            },
        ),
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_title', models.CharField(max_length=200, verbose_name='Título')),
                ('prog_slug', models.SlugField(verbose_name='Atalho')),
                ('prog_text', models.TextField(verbose_name='Texto')),
                ('prog_img1', models.ImageField(blank=True, null=True, upload_to='portfolio_posts/images', verbose_name='Imagem1')),
                ('prog_img2', models.ImageField(blank=True, null=True, upload_to='portfolio_posts/images', verbose_name='Imagem2')),
                ('prog_published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'ordering': ['prog_published_date'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_title', models.CharField(max_length=200, verbose_name='Título')),
                ('proj_slug', models.SlugField(verbose_name='Atalho')),
                ('proj_text', models.TextField(verbose_name='Texto')),
                ('proj_img1', models.ImageField(blank=True, null=True, upload_to='portfolio_posts/images', verbose_name='Imagem1')),
                ('proj_img2', models.ImageField(blank=True, null=True, upload_to='portfolio_posts/images', verbose_name='Imagem2')),
                ('proj_img3', models.ImageField(blank=True, null=True, upload_to='portfolio_posts/images', verbose_name='Imagem3')),
                ('proj_published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['proj_published_date'],
            },
        ),
    ]
