# Generated by Django 3.1.3 on 2020-11-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='art_img3',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_posts/images', verbose_name='Certificado Apresentação'),
        ),
    ]
