# Generated by Django 3.1.3 on 2020-11-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_posts', '0002_artigo_art_img3'),
    ]

    operations = [
        migrations.AddField(
            model_name='eletronica',
            name='el_img4',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_posts/images', verbose_name='Imagem3'),
        ),
        migrations.AddField(
            model_name='eletronica',
            name='el_img5',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_posts/images', verbose_name='Imagem3'),
        ),
    ]
