# Generated by Django 3.1.3 on 2020-11-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_posts', '0003_auto_20201128_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programacao',
        ),
    ]
