# Generated by Django 3.1.3 on 2021-01-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_posts', '0004_delete_programacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='portfolio_posts/images', verbose_name='Imagem')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título da imagem')),
            ],
        ),
    ]
