# Generated by Django 3.1.3 on 2021-01-11 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_posts', '0005_galeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Imagem_projeto', to='portfolio_posts.projeto'),
        ),
    ]
