# Generated by Django 3.1.3 on 2021-01-11 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_posts', '0006_galeria_projeto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Galeria',
            new_name='GaleriaProjeto',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='proj_img1',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='proj_img2',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='proj_img3',
        ),
    ]
