# Generated by Django 3.1.3 on 2021-01-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_posts', '0007_auto_20210111_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='proj_img1',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_posts/images', verbose_name='Imagem1'),
        ),
    ]
